version: '1.0'
stages:
- checkout
- build
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: 'XueGongZi/project_euler'
    revision: 'master'
    git: github
  build_my_app:
    title: Building Python Docker Image
    type: build
    stage: build
    image_name: my-python-app
    working_directory: '.'
    tag: 'master'
    dockerfile: Dockerfile
